name: ✨ Feature Request
description: Suggest a new feature for Claude.Orchestrator
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Alternatively, we could...

  - type: dropdown
    id: components
    attributes:
      label: Which components would this affect?
      multiple: true
      options:
        - Context Management
        - Workflow Engine
        - Performance Analytics
        - CLI Interface
        - API/SDK
        - Documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, mockups, or examples